import sys
from pathlib import Path
from sqlalchemy import Column, Integer, String, Float, Index

backend_dir = Path(__file__).resolve().parent.parent.parent
if str(backend_dir) not in sys.path:
    sys.path.append(str(backend_dir))

from app.database import Base


class FieldingStats(Base):
    """Per-player, per-season, per-position fielding statistics.

    Sources:
    - Historical rows (year < CURRENT_YEAR): loaded from
      ``mlb_fielding_data_2000_2025_with_statcast.csv``
    - Projected rows (year >= CURRENT_YEAR): loaded from
      ``fielding_projections_complete.csv`` (generated by the value
      determination pipeline).
    """
    __tablename__ = "fielding_stats"

    id = Column(Integer, primary_key=True, index=True)

    # Identity
    idfg = Column(Integer, index=True)         # FanGraphs player ID
    mlb_id = Column(Integer, index=True)       # MLB.com (mlbam) ID
    name = Column(String)
    season = Column(Integer, index=True)
    team = Column(String)
    pos = Column(String, index=True)           # e.g. SS, 2B, CF, C
    age = Column(Float)

    # Playing time
    g = Column(Integer)                        # Games at this position
    gs = Column(Integer)                       # Games started
    inn = Column(Float)                        # Innings at position

    # Statcast run values (per 150 for projections, raw for historical)
    sc_total_runs = Column(Float)              # Total defensive runs
    sc_range_runs = Column(Float)              # Range contribution
    sc_arm_runs = Column(Float)                # Arm contribution
    sc_dp_runs = Column(Float)                 # Double-play contribution (IF)
    sc_framing_runs = Column(Float)            # Framing runs (C)
    sc_throwing_runs = Column(Float)           # Throwing runs (C)
    sc_blocking_runs = Column(Float)           # Blocking runs (C)

    # Traditional / advanced
    drs = Column(Float)                        # Defensive Runs Saved
    uzr = Column(Float)                        # Ultimate Zone Rating
    uzr_150 = Column(Float)                    # UZR/150
    oaa = Column(Integer)                      # Outs Above Average

    # Errors
    errors = Column(Integer)
    fp = Column(Float)                         # Fielding percentage

    # Source flag
    is_projection = Column(Integer, default=0) # 0 = historical, 1 = projected

    __table_args__ = (
        Index("idx_fielding_idfg_season", "idfg", "season"),
        Index("idx_fielding_mlb_season", "mlb_id", "season"),
        Index("idx_fielding_projection", "is_projection"),
    )

    def __repr__(self):
        return f"<FieldingStats {self.name} {self.season} {self.pos}>"
