[build]
  base = "web-app/frontend"  # Change this line
  command = "npm ci && npm run build"
  publish = "web-app/frontend/dist"  # Update this too

[build.environment]
  VITE_API_URL = "https://43f4-71-212-206-128.ngrok-free.app"
  VITE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200