import React from 'react'
import { FaGithub } from 'react-icons/fa'

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-14">
    <h2 className="text-xl font-bold text-gray-900 font-display tracking-tight mb-4 pb-2 border-b border-gray-200">{title}</h2>
    <div className="space-y-4 text-[15px] text-gray-600 leading-relaxed">{children}</div>
  </section>
)

const About = () => {
  return (
    <div className="min-h-screen w-full bg-[#F5F3EE]">
      <main className="w-full">
        <div className="max-w-3xl mx-auto px-6 py-12">

          {/* Header */}
          <div className="mb-14">
            <h1 className="font-display text-4xl font-extrabold text-gray-900 tracking-tight mb-3">About LongBall</h1>
            <p className="text-lg text-gray-500 mb-6">
              An open-source platform for quantifying MLB trade value through long-term player projections, contract analysis, and surplus value modeling.
            </p>
            <a
              href="https://github.com/nielsjsc/LSTMLB"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-4 py-2 rounded-md bg-gray-900 hover:bg-gray-800 transition-colors text-white text-sm font-medium"
            >
              <FaGithub className="h-4 w-4" />
              <span>View on GitHub</span>
            </a>
          </div>

          {/* Motivation */}
          <Section title="Motivation">
            <p>
              Trade value is one of the most discussed yet least quantified concepts in baseball. Every deadline deal prompts debate about who "won" a trade, but there is no publicly available, systematic framework for assigning dollar values to players on the trade market. This project attempts to build one.
            </p>
            <p>
              Computing trade value requires two things: projected future on-field production (WAR) and projected future salary obligations. The difference between the two — surplus value — captures how much value a team receives above what it pays. But surplus alone does not fully explain trade behavior. A player with 3 projected WAR and $5M in surplus is not equivalent to a player with 1 projected WAR and the same surplus. Scarcity, roster concentration, and certainty all matter. This project models that distinction.
            </p>
          </Section>

          {/* Projection Models */}
          <Section title="Projection Models">
            <p>
              Player projections are generated by a family of bidirectional LSTM neural networks, each specialized for a different aspect of player performance: hitting, starting pitching, relief pitching, baserunning, infield defense, outfield defense, and catcher defense.
            </p>
            <p>
              Each model consumes a three-season sliding window of rate statistics and produces projections for the following season. Multi-year forecasts are generated autoregressively — each prediction becomes input for the next. A key architectural decision is <strong>delta prediction</strong>: rather than predicting absolute stat lines, the model predicts year-over-year changes from the player's last observed season. This prevents the autoregressive loop from regressing every player toward league average over long horizons.
            </p>

            <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wide mt-6 mb-2">Hitting</h3>
            <p>
              The batter model uses a two-stage transfer learning approach. Stage one pre-trains on classical features (BB%, K%, AVG, OBP, SLG, wOBA, and per-150 counting stats) using data back to 1950. Stage two fine-tunes on the Statcast era (2015+), expanding the feature set to include expected stats (xwOBA, xBA, xSLG) and batted-ball metrics (EV50, sweet-spot rate). LSTM layers are frozen during fine-tuning so only the output projection adapts to the new features, preserving the temporal patterns learned from 75 years of data.
            </p>
            <p>
              Counting stats (HR, 2B, 3B, RBI, R) are not taken directly from the model's output. Instead, they are derived from the model's predicted wOBA, scaled by each player's career counting-stat profile. This preserves individual power/speed signatures — a player who generates his wOBA through home runs will continue to do so in projections, rather than being assigned a generic league-average distribution.
            </p>

            <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wide mt-6 mb-2">Pitching</h3>
            <p>
              Separate models are trained for starting pitchers and relievers. Features include K%, BB%, HBP%, BABIP, FIP, ERA, ground ball rate, fly ball rate, HR/FB, SIERA (SP), and line drive rate. Post-prediction, ERA and FIP are reconstructed from component rates rather than taken as direct model outputs, producing internally consistent projections. Specifically, FIP is rebuilt from predicted K%, BB%, HBP%, and HR/FB, while ERA is derived from reconstructed FIP plus a James-Stein shrunk career ERA-FIP gap.
            </p>
            <p>
              Pitchers with Statcast data receive a quality adjustment based on Stuff+, Location+, and Pitching+ — peripheral indicators that predict future performance better than results alone. These adjustments nudge rate stats (e.g., a Stuff+ of 120 adds roughly 2.4 percentage points to projected K%) without requiring a full Statcast fine-tuning stage.
            </p>

            <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wide mt-6 mb-2">Defense and Baserunning</h3>
            <p>
              Defensive models use Statcast fielding run values (total runs, range runs, arm runs, and double-play runs for infielders) rather than legacy metrics like DRS or UZR. Separate models handle infield, outfield, and catcher defense. Baserunning is modeled from Statcast baserunning run values, stolen base rates, and caught stealing rates.
            </p>
          </Section>

          {/* Data Pipeline */}
          <Section title="Data Pipeline">
            <p>
              All statistics are normalized to rate form before model input. Batting stats are converted to per-150 games, pitcher stats to per-batter-faced, and defensive stats to per-1350 innings. This allows the model to learn performance level independent of playing time, which is projected separately.
            </p>
            <p>
              A reliability regression module applies James-Stein shrinkage to small samples before prediction. Each stat has a research-based stabilization point (e.g., K% stabilizes at 60 PA, wOBA at 200 PA, BABIP at 1200 batters faced). Players below these thresholds are regressed toward a recency-weighted career prior blended with the league average. Park factors, sourced from FanGraphs five-year averages, neutralize stats on input and re-apply them when calculating WAR.
            </p>
            <p>
              Empirical aging curves are derived from within-player year-over-year deltas using the paired difference method, with a correction for survivorship bias — the tendency for poor performers to exit the dataset at higher rates, which causes raw age curves to understate true decline.
            </p>
          </Section>

          {/* WAR Calculation */}
          <Section title="WAR Calculation">
            <p>
              Position player WAR is computed from batting runs (using FanGraphs wOBA weights and park-adjusted wRC+), baserunning runs, defensive runs, and positional adjustments, divided by a runs-per-win conversion factor. Pitcher WAR uses FIP-based methodology with a dynamic runs-per-win denominator — an ace who pitches deep into games suppresses the overall run environment, making each run saved more valuable in terms of wins.
            </p>
            <p>
              Players are projected at 150 games for position players (135 for catchers), 32 starts for starting pitchers, and 65 innings for relievers. While injuries and playing time are significant components of player value, they are difficult to predict reliably and are not currently modeled.
            </p>
          </Section>

          {/* Trade Value */}
          <Section title="From WAR to Trade Value">
            <p>
              WAR is converted to dollars using a convex power-law model: <span className="font-mono text-sm text-gray-700">$8.59M x WAR<sup>1.18</sup></span>, with 4% annual inflation from a 2025 base. The exponent greater than one captures the superlinear pricing of high-WAR players — a five-win player commands substantially more on the trade market than five one-win players. The parameters were calibrated by minimizing median absolute trade imbalance across 744 MLB trades from 2014 to 2024.
            </p>
            <p>
              Trade value is then the sum of projected WAR dollar values over a player's remaining team-control years, minus projected salary obligations. Pre-arbitration players are valued at $720K per year. Arbitration salaries are estimated as a percentage of market value (15% for Arb-1, 25% for Arb-2, 40% for Arb-3). Contract options (player, team, vesting, and opt-outs) are evaluated and incorporated into the timeline.
            </p>
          </Section>

          {/* Prospect Valuations */}
          <Section title="Prospect Valuations">
            <p>
              Prospects without significant MLB track records are valued using FanGraphs FV grades and consensus ranking data. Base values range from $1M (30 FV) to $120M (70 FV), with a top-100 ranking multiplier that scales from 1.5x at rank 1 down to 1.0x at rank 100. As prospects accumulate MLB playing time, their valuation transitions linearly from the FV-based estimate to the projection-based estimate over the first 300 games (batters), 45 starts (SP), or 65 appearances (RP).
            </p>
            <p>
              A separate MiLB projection model uses minor league rate statistics with level-adjusted priors (accounting for the empirical translation rates between levels) to estimate future MLB performance for players still in the minor league system.
            </p>
          </Section>

          {/* Bayesian Model */}
          <Section title="Bayesian Aging Model">
            <p>
              An independent Bayesian hierarchical model, implemented in NumPyro, provides a second opinion on aging trajectories. It estimates population-level aging curve parameters (peak age, decline rate) and player-specific deviations using a three-level hierarchy. PA-weighting in the likelihood ensures that a 600-PA season constrains a player's talent estimate far more tightly than a 100-PA season, without arbitrary cutoffs.
            </p>
            <p>
              The model is fit in two stages: population aging parameters are learned from 1950-2020 data to avoid leakage, then current player projections use only 2021-2025 data with the learned curve as a prior.
            </p>
          </Section>

          {/* Limitations */}
          <Section title="Limitations">
            <p>
              Long-range player projections are inherently uncertain. No model can predict injuries, role changes, mechanical adjustments, or the dozens of other factors that alter a career trajectory. The projections presented here represent a statistical expectation conditional on continued health and opportunity — they are not predictions of what will happen, but estimates of baseline expected value.
            </p>
            <p>
              Playing time is assumed rather than predicted. The WAR-to-dollar model, while calibrated on real trades, reflects average market behavior and cannot capture the idiosyncratic preferences of individual front offices. Prospect valuations rely on consensus scouting grades that update annually and can shift substantially between seasons.
            </p>
          </Section>

          {/* Tech Stack */}
          <section className="mb-14">
            <h2 className="text-xl font-bold text-gray-900 font-display tracking-tight mb-4 pb-2 border-b border-gray-200">Technical Stack</h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-8 gap-y-2 text-[15px] text-gray-600">
              <div><span className="text-gray-400">Models</span> <span className="ml-2">PyTorch, NumPyro</span></div>
              <div><span className="text-gray-400">Backend</span> <span className="ml-2">FastAPI, SQLAlchemy</span></div>
              <div><span className="text-gray-400">Frontend</span> <span className="ml-2">React, TypeScript</span></div>
              <div><span className="text-gray-400">Data</span> <span className="ml-2">Statcast, FanGraphs, Spotrac</span></div>
              <div><span className="text-gray-400">Database</span> <span className="ml-2">SQLite</span></div>
              <div><span className="text-gray-400">Styling</span> <span className="ml-2">Tailwind CSS</span></div>
            </div>
          </section>

          {/* Footer */}
          <div className="text-sm text-gray-400 pt-6 border-t border-gray-200">
            All models and data pipelines are open source under the MIT license. Contributions and feedback are welcome on GitHub.
          </div>

        </div>
      </main>
    </div>
  )
}

export default About