"""Inital migration

Revision ID: b0c7e913fa67
Revises: 
Create Date: 2025-02-22 17:50:26.752823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c7e913fa67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('base_value', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('surplus_value', sa.Float(), nullable=True),
    sa.Column('trade_value', sa.Float(), nullable=True),
    sa.Column('fa_year', sa.Integer(), nullable=True),
    sa.Column('probable_fa_year', sa.Integer(), nullable=True),
    sa.Column('earliest_fa_year', sa.Integer(), nullable=True),
    sa.Column('contract_war', sa.Float(), nullable=True),
    sa.Column('avg_war', sa.Float(), nullable=True),
    sa.Column('total_contract', sa.Float(), nullable=True),
    sa.Column('avg_contract', sa.Float(), nullable=True),
    sa.Column('years_control', sa.Integer(), nullable=True),
    sa.Column('control_through', sa.Integer(), nullable=True),
    sa.Column('total_future_war', sa.Float(), nullable=True),
    sa.Column('total_future_value', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_war', sa.Float(), nullable=True),
    sa.Column('historical_value', sa.Float(), nullable=True),
    sa.Column('historical_war', sa.Float(), nullable=True),
    sa.Column('contract_base_value', sa.Float(), nullable=True),
    sa.Column('g_bat', sa.Integer(), nullable=True),
    sa.Column('war_bat', sa.Float(), nullable=True),
    sa.Column('bb_pct_bat', sa.Float(), nullable=True),
    sa.Column('k_pct_bat', sa.Float(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('woba', sa.Float(), nullable=True),
    sa.Column('wrc_plus', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('off', sa.Float(), nullable=True),
    sa.Column('bsr', sa.Float(), nullable=True),
    sa.Column('def_value', sa.Float(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('r', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('cs', sa.Integer(), nullable=True),
    sa.Column('g_pit', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('war_pit', sa.Float(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('siera', sa.Float(), nullable=True),
    sa.Column('k_pct_pit', sa.Float(), nullable=True),
    sa.Column('bb_pct_pit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_year_position', 'players', ['year', 'position'], unique=False)
    op.create_index('idx_year_team', 'players', ['year', 'team'], unique=False)
    op.create_index('idx_year_war_bat', 'players', ['year', 'war_bat'], unique=False)
    op.create_index('idx_year_war_pit', 'players', ['year', 'war_pit'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_real_id'), 'players', ['real_id'], unique=False)
    op.create_index(op.f('ix_players_team'), 'players', ['team'], unique=False)
    op.create_index(op.f('ix_players_year'), 'players', ['year'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IDfg', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('has_mlb', sa.Boolean(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('fv', sa.String(), nullable=True),
    sa.Column('hit', sa.String(), nullable=True),
    sa.Column('game_power', sa.String(), nullable=True),
    sa.Column('raw_power', sa.String(), nullable=True),
    sa.Column('speed', sa.String(), nullable=True),
    sa.Column('fastball', sa.String(), nullable=True),
    sa.Column('slider', sa.String(), nullable=True),
    sa.Column('curve', sa.String(), nullable=True),
    sa.Column('changeup', sa.String(), nullable=True),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('value_2022', sa.Float(), nullable=True),
    sa.Column('value_2023', sa.Float(), nullable=True),
    sa.Column('value_2024', sa.Float(), nullable=True),
    sa.Column('value_2025', sa.Float(), nullable=True),
    sa.Column('composite_2022', sa.Float(), nullable=True),
    sa.Column('composite_2023', sa.Float(), nullable=True),
    sa.Column('composite_2024', sa.Float(), nullable=True),
    sa.Column('composite_2025', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_IDfg'), 'prospects', ['IDfg'], unique=False)
    op.create_index(op.f('ix_prospects_id'), 'prospects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospects_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_IDfg'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_players_year'), table_name='players')
    op.drop_index(op.f('ix_players_team'), table_name='players')
    op.drop_index(op.f('ix_players_real_id'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index('idx_year_war_pit', table_name='players')
    op.drop_index('idx_year_war_bat', table_name='players')
    op.drop_index('idx_year_team', table_name='players')
    op.drop_index('idx_year_position', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
